<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE USUARIOS [
<!ELEMENT USUARIOS (usuario+)>
<!ELEMENT usuario (nombre,email,password,genero)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ATTLIST usuario id CDATA #REQUIRED>
<!ATTLIST usuario tipo (Administrator|Professor|Student) #REQUIRED>
]>
<USUARIOS>
  <usuario id="0" tipo="Administrator">
    <nombre>Joel Romero</nombre>
    <email>joelrg1288@gmail.com</email>
    <password>12345678</password>
    <genero>Male</genero>
  </usuario>
  <usuario id="1" tipo="Administrator">
    <nombre>Yamani Alvarez</nombre>
    <email>yamalvarez23@gmail.com</email>
    <password>12345678</password>
    <genero>Female</genero>
  </usuario>
  <usuario id="2" tipo="Professor">
    <nombre>Ruben Peredo</nombre>
    <email>ruben@hotmail.com</email>
    <password>098765432</password>
    <genero>Male</genero>
  </usuario>
  <usuario id="3" tipo="Student">
    <nombre>Companiero Ibaniez</nombre>
    <email>ibaniez@hotmail.com</email>
    <password>poiuytrewq</password>
    <genero>Male</genero>
  </usuario>
</USUARIOS>
